table Date
	isHidden
	lineageTag: 126885d6-370a-4e0e-8ab7-ddb74f70fd3c

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: ba28851e-c929-4da1-8137-c8d1d8f54cda
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d9f73cb5-8691-4aa4-90ed-0a5ae8959363
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e6f99023-0290-4308-a9f1-8b62eea7003c
		summarizeBy: none
		sourceColumn: Quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0e89092a-2f7f-45a6-982d-cbdcf12a9b4b
		summarizeBy: none
		sourceColumn: Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		isHidden
		lineageTag: 8746d583-8c73-4a74-ba23-e25e8ff6b69f
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: Month

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Start of Year'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 9badb5a7-03bb-4e3b-8496-3cb940ed50f9
		summarizeBy: none
		sourceColumn: Start of Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Year'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: cc6bac04-deb1-4111-ac62-6cfbb66a9f3d
		summarizeBy: none
		sourceColumn: End of Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Month'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: d8f7b1ed-6f7a-4433-a900-f5abd1e6b384
		summarizeBy: none
		sourceColumn: Start of Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Month'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 1dd682a3-af4a-4a4f-9ca2-7207094bc141
		summarizeBy: none
		sourceColumn: End of Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Days in Month'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9e9bdd5d-9743-4f88-885e-0fd31784a37b
		summarizeBy: none
		sourceColumn: Days in Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4649cf0d-fc01-41e8-9853-cffea8305b91
		summarizeBy: none
		sourceColumn: Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		isHidden
		lineageTag: bf533414-02c5-4bf7-a1dd-afac07b29be0
		summarizeBy: none
		sourceColumn: Day Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0f2ee9fe-4c90-4294-b545-291a23da5a35
		summarizeBy: none
		sourceColumn: Day of Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day of Year'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 87605509-e9a9-4972-b893-4309d249ccb2
		summarizeBy: none
		sourceColumn: Day of Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Start of Quarter'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: c010320a-f639-4f83-b75f-9cee2d70a257
		summarizeBy: none
		sourceColumn: Start of Quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Quarter'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: cb7ecd75-1312-4197-bccf-72d0a1f81e13
		summarizeBy: none
		sourceColumn: End of Quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Week of Year'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d38d1b18-b2db-40c9-825b-32cddeebcc94
		summarizeBy: none
		sourceColumn: Week of Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Week of Month'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e0a9b6af-0f17-45f0-aef7-4e2961b303e8
		summarizeBy: none
		sourceColumn: Week of Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Start of Week'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 79e3adb3-e645-46e7-aeef-a574692fc6ed
		summarizeBy: none
		sourceColumn: Start of Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End of Week'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 790e8a21-8cc9-47b2-8756-293e2cfada55
		summarizeBy: none
		sourceColumn: End of Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fedc7038-40dd-4cb1-a877-aa9bae731586
		summarizeBy: none
		sourceColumn: Fiscal Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c867f39a-e848-4424-9172-f0f8382725eb
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 25d25df2-df91-4e6c-ba41-20b915a7b09b
		summarizeBy: none
		sourceColumn: Fiscal Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day Offset'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a80f7f38-84be-4720-b7c4-2af25a462294
		summarizeBy: none
		sourceColumn: Day Offset

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Offset'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b9adb5de-a41b-4ca0-a662-3eae5c4cd505
		summarizeBy: none
		sourceColumn: Month Offset

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Year Offset'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 88d00009-1b82-4833-82df-c10c7878ffcd
		summarizeBy: none
		sourceColumn: Year Offset

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Quarter Offset'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bd0f23df-f615-4da8-96ea-e747d95b8d42
		summarizeBy: none
		sourceColumn: Quarter Offset

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year-Month
		dataType: string
		isHidden
		lineageTag: 9131aadb-83b1-47b6-be5d-2bf71561272a
		summarizeBy: none
		sourceColumn: Year-Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Year-Month Code'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ee5fc970-49a7-43a7-9e57-b243d2ec60db
		summarizeBy: none
		sourceColumn: Year-Month Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Date-8867d621-1745-42cf-91f7-ebaf87468299 = m
		mode: import
		source =
				let
				    // configurations start
				    Today=Date.From(DateTime.LocalNow()), // today's date
				    FromYear = 2008, // set the start year of the date dimension. dates start from 1st of January of this year
				    ToYear=2021, // set the end year of the date dimension. dates end at 31st of December of this year
				    StartofFiscalYear=7, // set the month number that is start of the financial year. example; if fiscal year start is July, value is 7
				    firstDayofWeek=Day.Monday, // set the week's start day, values: Day.Monday, Day.Sunday....
				    // configuration end
				    FromDate=#date(FromYear,1,1),
				    ToDate=#date(ToYear,12,31),
				    Source=List.Dates(
				        FromDate,
				        Duration.Days(ToDate-FromDate)+1,
				        #duration(1,0,0,0)
				    ),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Start of Year" = Table.AddColumn(#"Inserted Year", "Start of Year", each Date.StartOfYear([Date]), type date),
				    #"Inserted End of Year" = Table.AddColumn(#"Inserted Start of Year", "End of Year", each Date.EndOfYear([Date]), type date),
				    #"Inserted Month" = Table.AddColumn(#"Inserted End of Year", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Month", "Start of Month", each Date.StartOfMonth([Date]), type date),
				    #"Inserted End of Month" = Table.AddColumn(#"Inserted Start of Month", "End of Month", each Date.EndOfMonth([Date]), type date),
				    #"Inserted Days in Month" = Table.AddColumn(#"Inserted End of Month", "Days in Month", each Date.DaysInMonth([Date]), Int64.Type),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Days in Month", "Day", each Date.Day([Date]), Int64.Type),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day Name", "Day of Week", each Date.DayOfWeek([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Day of Year", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Inserted Start of Quarter" = Table.AddColumn(#"Inserted Quarter", "Start of Quarter", each Date.StartOfQuarter([Date]), type date),
				    #"Inserted End of Quarter" = Table.AddColumn(#"Inserted Start of Quarter", "End of Quarter", each Date.EndOfQuarter([Date]), type date),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted End of Quarter", "Week of Year", each Date.WeekOfYear([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([Date],firstDayofWeek), Int64.Type),
				    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Week of Month", "Start of Week", each Date.StartOfWeek([Date],firstDayofWeek), type date),
				    #"Inserted End of Week" = Table.AddColumn(#"Inserted Start of Week", "End of Week", each Date.EndOfWeek([Date],firstDayofWeek), type date),
				    FiscalMonthBaseIndex=13-StartofFiscalYear,
				    adjustedFiscalMonthBaseIndex=if(FiscalMonthBaseIndex>=12 or FiscalMonthBaseIndex<0) then 0 else FiscalMonthBaseIndex,
				    #"Added Custom" = Table.AddColumn(#"Inserted End of Week", "FiscalBaseDate", each Date.AddMonths([Date],adjustedFiscalMonthBaseIndex)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"FiscalBaseDate", type date}}),
				    #"Inserted Year1" = Table.AddColumn(#"Changed Type1", "Year.1", each Date.Year([FiscalBaseDate]), Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Year1",{{"Year.1", "Fiscal Year"}}),
				    #"Inserted Quarter1" = Table.AddColumn(#"Renamed Columns1", "Quarter.1", each Date.QuarterOfYear([FiscalBaseDate]), Int64.Type),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Quarter1",{{"Quarter.1", "Fiscal Quarter"}}),
				    #"Inserted Month1" = Table.AddColumn(#"Renamed Columns2", "Month.1", each Date.Month([FiscalBaseDate]), Int64.Type),
				    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Month1",{{"Month.1", "Fiscal Month"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns3",{"FiscalBaseDate"}),
				    #"Inserted Age" = Table.AddColumn(#"Removed Columns", "Age", each [Date]-Today, type duration),
				    #"Extracted Days" = Table.TransformColumns(#"Inserted Age",{{"Age", Duration.Days, Int64.Type}}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Extracted Days",{{"Age", "Day Offset"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns4", "Month Offset", each (([Year]-Date.Year(Today))*12)
				+([Month]-Date.Month(Today))),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Month Offset", Int64.Type}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "Year Offset", each [Year]-Date.Year(Today)),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom2",{{"Year Offset", Int64.Type}}),
				    #"Added Custom3" = Table.AddColumn(#"Changed Type3", "Quarter Offset", each (([Year]-Date.Year(Today))*4)
				+([Quarter]-Date.QuarterOfYear(Today))),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom3",{{"Quarter Offset", Int64.Type}}),
				    #"Added Custom4" = Table.AddColumn(#"Changed Type4", "Year-Month", each Date.ToText([Date],"MMM yyyy")),
				    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "Year-Month Code", each Date.ToText([Date],"yyyyMM")),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom5",{{"Year-Month", type text}, {"Year-Month Code", Int64.Type}})
				in
				    #"Changed Type5"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

